AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-api

  Sample SAM Template for cloud-resume-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CloudResumeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cloud-resume/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies:
      # Give your Lambda full access to DynamoDB
      - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        CloudResume:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /counter
            Method: get
  CloudResumeTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cloudresume-table
      PrimaryKey:
        Name: id
        Type: Number
        


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CloudResumeApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter/"
  CloudResumeFunction:
    Description: "CloudResume Lambda Function ARN"
    Value: !GetAtt CloudResumeFunction.Arn
  CloudResumeFunctionIamRole:
    Description: "Implicit IAM Role created for Cloud Resume function"
    Value: !GetAtt CloudResumeFunctionRole.Arn
